### ISSUE TITLE
gulp plugin not including css in aggregated css

### ISSUE THREAD

**Issue by nadavelyashiv** [iameugenejo/angular-centered#3]
I'm using gulp to build my application.
I have a task that takes the CSS files from bower_components and builds vendor.css from all.
I noticed angular-centered css is not going in there automatically.
I think the difference is that every module stated the css in bower.json in "main" property and you didn't.
Is it possible to fix?
thank you

**Comment by iameugenejo** [comment]
Thanks for pointing it out. I added the css in the config.

Please uninstall / install angular-centered again and see if it works.

**Comment by nadavelyashiv** [comment]
Your CSS is causing my gulp CSS task to fail for illegal CSS, it doesn't state a specific reason (or line).

**Comment by iameugenejo** [comment]
Sorry about that, I didn't realize someone contributed with a commit  containing an invalid css (he used SASS syntax).

I just fixed it, so please try it again.
